title: SMARSLab Documentation
email: kevinmcaleer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  SMARSLab - a browser based user interface for SMARS robots
baseurl: "/SMARSLab" # the subpath of your site, e.g. /blog
url: "https://kevinmcaleer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kevsmac
github_username:  kevinmcaleer

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - data_page_generator
  - jekyll-redirect-from

permalink: /:categories/:slug.html
sass:
  style: :compressed

gems:
  - jekyll-octicons
